# NumPy Exercises — 50 Problems

**Instructions:**
- Run the first cell to import NumPy before starting.
- Each exercise has a **Question** and an **Input** (where given).
- Write your solution in the `# Write your code here:` cell below each question.
- Run your cell to check your output.
- Do **not** modify the Input cells or the import cell.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [184]:
# Run this cell before starting — do not modify
import numpy as np

## Section 1 — Array Basics (Exercises 1–10)

### Exercise 1 — NumPy Version

**Question:** Print the version of NumPy.


In [185]:
print(np.__version__)


2.0.2


### Exercise 2 — 1D Array

**Question:** Create a 1D array of numbers from 0 to 9.


In [186]:
arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


### Exercise 3 — Boolean Array

**Question:** Create a 3×3 NumPy array of all `True`s.


In [187]:
bool_arr = np.ones((3, 3), dtype=bool)
print(bool_arr)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Exercise 4 — Filter Odd Numbers

**Question:** Extract all odd numbers from `arr`.


In [188]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [189]:
# Write your code here:
odd_nums = arr[arr % 2 == 1]
print(odd_nums)

[1 3 5 7 9]


### Exercise 5 — Replace In-Place

**Question:** Replace all odd numbers in `arr` with `-1`.


In [190]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [191]:
# Write arr[arr % 2 == 1] = -1
arr[arr % 2 == 1] = -1
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 6 — Replace Without Modifying Original

**Question:** Replace all odd numbers in `arr` with `-1` **without** changing the original array.


In [192]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [193]:
# Write your code here:
out = np.where(arr % 2 == 1, -1, arr)
print(out)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 7 — Reshape Array

**Question:** Convert a 1D array to a 2D array with 2 rows.


In [194]:
# Input — do not modify
arr = np.arange(10)

In [195]:
# Write your code here:
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Exercise 8 — Vertical Stack

**Question:** Stack arrays `a` and `b` vertically.


In [196]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [197]:
# Write your code here:
stacked_v = np.vstack((a, b))
print(stacked_v)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Exercise 9 — Horizontal Stack

**Question:** Stack arrays `a` and `b` horizontally.


In [198]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [199]:
# Write your code here:
stacked_h = np.hstack((a, b))
print(stacked_h)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Exercise 10 — Custom Sequence

**Question:** Create the following pattern **without hardcoding**. Use only NumPy functions and the input array `a`.

Expected output: `array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`


In [200]:
# Input — do not modify
a = np.array([1, 2, 3])

In [201]:
# Write your code here:
pattern = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(pattern)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## Section 2 — Set Operations & Filtering (Exercises 11–19)

### Exercise 11 — Common Items

**Question:** Get the common items between arrays `a` and `b`.


In [202]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [203]:
# Write your code here:
common = np.intersect1d(a, b)
print(common)

[2 4]


### Exercise 12 — Remove Items

**Question:** From array `a`, remove all items present in array `b`.


In [204]:
# Input — do not modify
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [205]:
# Write your code here:
diff = np.setdiff1d(a, b)
print(diff)

[1 2 3 4]


### Exercise 13 — Matching Positions

**Question:** Get the positions where elements of `a` and `b` match.


In [206]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [207]:
# Write your code here:
positions = np.where(a == b)
print(positions)

(array([1, 3, 5, 7]),)


### Exercise 14 — Extract Range

**Question:** Get all items between 5 and 10 from array `a`.


In [208]:
# Input — do not modify
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [209]:
# Write your code here:
extracted = a[(a >= 5) & (a <= 10)]
print(extracted)

[ 6  9 10]


### Exercise 15 — Vectorize a Function

**Question:** Convert the scalar function `maxx` below to work on two arrays.


In [210]:
# Input — do not modify
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [211]:
# Write your code here:
pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


### Exercise 16 — Swap Columns

**Question:** Swap columns 1 and 2 in array `arr`.


In [212]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [213]:
# Write your code here:
arr_swapped = arr[:, [0, 2, 1]]
print(arr_swapped)

[[0 2 1]
 [3 5 4]
 [6 8 7]]


### Exercise 17 — Swap Rows

**Question:** Swap rows 1 and 2 in array `arr`.


In [214]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [215]:
# Write your code here:
arr_swapped = arr[[0, 2, 1], :]
print(arr_swapped)

[[0 1 2]
 [6 7 8]
 [3 4 5]]


### Exercise 18 — Reverse Rows

**Question:** Reverse the rows of the 2D array `arr`.


In [216]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [217]:
# Write your code here:
reversed_rows = arr[::-1]
print(reversed_rows)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


### Exercise 19 — Reverse Columns

**Question:** Reverse the columns of the 2D array `arr`.


In [218]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [219]:
# Write your code here:
reversed_cols = arr[:, ::-1]
print(reversed_cols)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


## Section 3 — Printing & Formatting (Exercises 20–24)

### Exercise 20 — Random Float Array

**Question:** Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.


In [220]:
# Write your code here:
rand_arr = np.random.uniform(5, 10, size=(5, 3))
print(rand_arr)

[[6.494382 7.843728 5.893122]
 [7.662869 8.233457 5.710327]
 [7.906945 7.39595  6.932096]
 [7.202325 7.023787 7.21127 ]
 [5.150616 8.880027 7.754792]]


### Exercise 21 — Decimal Places

**Question:** Print only 3 decimal places of the array `rand_arr`.


In [221]:
# Input — do not modify
rand_arr = np.random.random((5,3))

In [222]:
# Write your code here:
np.set_printoptions(precision=3)
print(rand_arr)

[[0.381 0.529 0.957]
 [0.176 0.118 0.863]
 [0.075 0.825 0.836]
 [0.075 0.011 0.048]
 [0.357 0.666 0.011]]


### Exercise 22 — Suppress Scientific Notation

**Question:** Pretty print `rand_arr` by suppressing scientific notation (like `1e10`).


In [223]:
# Input — do not modify
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [224]:
# Write your code here:
np.set_printoptions(suppress=True, precision=6)
print(rand_arr)

[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


### Exercise 23 — Limit Print Output

**Question:** Limit the number of items printed in array `a` to a maximum of 6 elements.


In [225]:
# Input — do not modify
a = np.arange(15)

In [226]:
# Write your code here:
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


### Exercise 24 — Print Full Array

**Question:** Print the full NumPy array `a` without truncating.


In [227]:
# Input — do not modify
np.set_printoptions(threshold=6)
a = np.arange(15)

In [228]:
# Write your code here:
import sys
np.set_printoptions(threshold=sys.maxsize)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Section 4 — Iris Dataset (Exercises 25–46)

### Exercise 25 — Import Dataset

**Question:** Import the Iris dataset keeping the text intact.

> URL: `https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv`


In [229]:
# Write your code here:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
iris_data = np.genfromtxt(url, delimiter=',', dtype='object')
print(iris_data[:3])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


### Exercise 26 — Extract Text Column

**Question:** Extract the text column `species` from the 1D iris dataset imported in Exercise 25.

*# Make sure you have run Exercise 25 first so that iris_data is defined.*


In [230]:
# Write your code here:
species = iris_data[:, 4]
print(species[:5])

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


### Exercise 27 — 1D to 2D Array

**Question:** Convert the 1D iris dataset to a 2D array `iris_2d` by omitting the species text field.

*# Make sure you have run Exercise 25 first.*


In [231]:
# Write your code here:
iris_2d = iris_data[:, :-1].astype(float)
print(iris_2d[:3])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


### Exercise 28 — Mean, Median, Std

**Question:** Find the mean, median, and standard deviation of the sepal length (1st column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [232]:
# Write your code here:
sepal_length = iris_2d[:, 0]
print("Mean:", np.mean(sepal_length))
print("Median:", np.median(sepal_length))
print("Std:", np.std(sepal_length))

Mean: 5.843333333333334
Median: 5.8
Std: 0.8253012917851409


### Exercise 29 — Normalize Array

**Question:** Create a normalized form of iris's sepal length whose values range exactly between 0 and 1 (minimum → 0, maximum → 1).

*# Make sure you have run Exercise 27 first.*


In [233]:
# Write your code here:
s_min, s_max = sepal_length.min(), sepal_length.max()
normalized = (sepal_length - s_min) / (s_max - s_min)
print(normalized[:5])

[0.222222 0.166667 0.111111 0.083333 0.194444]


### Exercise 30 — Softmax Score

**Question:** Compute the softmax score of the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [234]:
# Write your code here:
softmax_score = np.exp(sepal_length) / np.sum(np.exp(sepal_length))
print(softmax_score[:5])

[0.00222  0.001817 0.001488 0.001346 0.002008]


### Exercise 31 — Percentile Scores

**Question:** Find the 5th and 95th percentile of iris's sepal length.

*# Make sure you have run Exercise 27 first.*


In [235]:
# Write your code here:
percentiles = np.percentile(sepal_length, [5, 95])
print(percentiles)

[4.6   7.255]


### Exercise 32 — Insert Missing Values

**Question:** Insert `np.nan` values at 20 random positions in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [236]:
# Write your code here:
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(iris_2d[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 nan 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


### Exercise 33 — Find Missing Values

**Question:** Find the **number** and **position** of missing values in `iris_2d`'s sepal length (1st column).

*# Make sure you have run Exercise 32 first.*


In [237]:
# Write your code here:
missing_pos = np.where(np.isnan(iris_2d[:, 0]))
missing_count = np.isnan(iris_2d[:, 0]).sum()

print("Position of missing values:", missing_pos[0])
print("Number of missing values:", missing_count)

Position of missing values: [14 34 79 87]
Number of missing values: 4


### Exercise 34 — Multi-Condition Filter

**Question:** Filter the rows of `iris_2d` that have:
- petal length (3rd column) > 1.5, **and**
- sepal length (1st column) < 5.0

*# Make sure you have run Exercise 32 first.*


In [238]:
# Write your code here:
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
filtered_rows = iris_2d[condition]
print(filtered_rows)

[[4.8 3.4 1.6 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


### Exercise 35 — Drop Rows with NaN

**Question:** Select rows of `iris_2d` that do **not** have any `nan` value.

*# Make sure you have run Exercise 32 first.*


In [239]:
# Write your code here:
clean_iris = iris_2d[~np.isnan(iris_2d).any(axis=1)]
print(clean_iris[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Exercise 36 — Correlation

**Question:** Find the correlation between sepal length (1st column) and petal length (3rd column) in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [240]:
# Write your code here:
sepal_len = clean_iris[:, 0]
petal_len = clean_iris[:, 2]
correlation = np.corrcoef(sepal_len, petal_len)[0, 1]
print("Correlation:", correlation)

Correlation: 0.8767822532905785


### Exercise 37 — Check for NaN

**Question:** Find out if `iris_2d` has any missing values.

*# Make sure you have run Exercise 32 first.*


In [241]:
# Write your code here:
has_nan = np.isnan(iris_2d).any()
print(has_nan)

True


### Exercise 38 — Replace NaN with 0

**Question:** Replace all occurrences of `nan` with `0` in `iris_2d`.

*# Make sure you have run Exercise 32 first.*


In [242]:
# Write your code here:
iris_2d[np.isnan(iris_2d)] = 0
print(np.isnan(iris_2d).any())

False


### Exercise 39 — Unique Value Counts

**Question:** Find the unique values and their counts in iris's species column.

*# Make sure you have run Exercise 25 first.*


In [243]:
# Write your code here:
unique_vals, counts = np.unique(species, return_counts=True)
print(unique_vals)
print(counts)

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']
[50 50 50]


### Exercise 40 — Numeric to Categorical

**Question:** Bin the petal length (3rd column) of `iris_2d` to form a text array using these rules:
- `< 3` → `'small'`
- `3–5` → `'medium'`
- `>= 5` → `'large'`

*# Make sure you have run Exercise 27 first.*


In [262]:
# Write your code here:
petal_lengths = iris_data[:, 2].astype(float)
conditions = [
    petal_lengths < 3,
    (petal_lengths >= 3) & (petal_lengths < 5),
    petal_lengths >= 5
]
categories = ['small', 'medium', 'large']

petal_categories = np.select(conditions, categories, default='unknown')
print(petal_categories[:10])

['small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small']


### Exercise 41 — Create New Column

**Question:** Create a new column for **volume** in `iris_2d`, where:

> volume = (π × petal_length × sepal_length²) / 3

*# Make sure you have run Exercise 27 first.*


In [247]:
# Write your code here:
petal_length = iris_2d[:, 2]
sepal_length = iris_2d[:, 0]
volume = (np.pi * petal_length * (sepal_length ** 2)) / 3

# Add as a new column at the end
iris_2d_vol = np.c_[iris_2d, volume]
print(iris_2d_vol[:3])

[[ 5.1       3.5       1.4       0.2      38.132652]
 [ 4.9       3.        1.4       0.2      35.200498]
 [ 4.7       3.2       1.3       0.2      30.072372]]


### Exercise 42 — Probabilistic Sampling

**Question:** Randomly sample iris's species such that **setosa** appears **twice** as often as versicolor and virginica.

*# Make sure you have run Exercise 25 first.*


In [248]:
# Write your code here:
# setosa=0.5, versicolor=0.25, virginica=0.25
probs = [0.5 if s == b'Iris-setosa' else 0.25 for s in unique_vals]

sampled = np.random.choice(['setosa', 'versicolor', 'virginica'], size=20, p=[0.5, 0.25, 0.25])
print(sampled)

['setosa' 'versicolor' 'setosa' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'virginica' 'versicolor' 'setosa' 'versicolor' 'virginica' 'setosa'
 'setosa']


### Exercise 43 — Second Largest Value

**Question:** Find the **second longest** petal length among iris samples of species **setosa**.

*# Make sure you have run Exercise 25 first.*


In [249]:
# Write your code here:

setosa_petals = iris_2d[species == b'Iris-setosa', 2]

second_largest = np.unique(np.sort(setosa_petals))[-2]
print(second_largest)

1.7


### Exercise 44 — Sort 2D Array by Column

**Question:** Sort the iris dataset based on the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [250]:
# Write your code here:

sorted_iris = iris_2d[iris_2d[:, 0].argsort()]
print(sorted_iris[:5])

[[0.  4.  1.2 0.2]
 [0.  3.1 1.5 0.1]
 [0.  2.3 4.4 1.3]
 [0.  2.6 3.5 1. ]
 [4.3 3.  1.1 0.1]]


### Exercise 45 — Most Frequent Value

**Question:** Find the most frequent value of petal length (3rd column) in the iris dataset.

*# Make sure you have run Exercise 27 first.*


In [251]:
# Write your code here:
vals, counts = np.unique(iris_2d[:, 2], return_counts=True)
most_frequent = vals[np.argmax(counts)]
print("Most frequent petal length:", most_frequent)

Most frequent petal length: 1.5


### Exercise 46 — First Value Greater Than

**Question:** Find the position of the **first occurrence** of a value greater than 1.0 in the petal width (4th column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [252]:
# Write your code here:
petal_width = iris_2d[:, 3]
first_pos = np.argwhere(petal_width > 1.0)[0]
print("First position:", first_pos[0])

First position: 50


## Section 5 — Miscellaneous (Exercises 47–50)

### Exercise 47 — Clip Values

**Question:** From array `a`, replace all values **greater than 30** with `30`, and all values **less than 10** with `10`.


In [253]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [254]:
# Write your code here:
clipped_a = np.clip(a, 10, 30)
print(clipped_a)

[27.626842 14.6401   21.801362 30.       10.       10.       30.
 30.       10.       29.179573 30.       11.250904 10.081083 10.
 11.765177 30.       30.       10.       30.       14.429614]


### Exercise 48 — Top N Positions

**Question:** Get the positions of the **top 5 maximum values** in array `a`.


In [ ]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [255]:
# Write your code here:
top_5_pos = a.argsort()[-5:][::-1]
print(top_5_pos)

[15 10  3  7 18]


### Exercise 49 — Row-wise Unique Counts

**Question:** Compute the counts of unique values **row-wise** in the input array.


In [ ]:
# Input — do not modify
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))

In [256]:
# Write your code here:
unique_counts = [len(np.unique(row)) for row in arr]
print(unique_counts)

[3, 3, 3]


### Exercise 50 — Flatten Array of Arrays

**Question:** Convert `arr_2d` (an array of arrays) into a flat 1D array.


In [ ]:
# Input — do not modify
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)
arr_2d = np.array([arr1, arr2, arr3], dtype=object)

In [257]:
# Write your code here:
flat_arr = np.concatenate(arr_2d)
print(flat_arr)

[0 1 2 3 4 5 6 7 8 9]


---

## 🎉 Well done!

You've completed all 50 exercises. Review any exercises you found tricky and revisit the NumPy documentation for deeper understanding.